### ISSUE TITLE
Player Names

### ISSUE THREAD

**Issue by vittz** [DanielPaulSwan/TestEmperorPenguin#11]
**Describe the bug**

Player names are appearing as "Player 1 (PlayerManager)" rather than just "Player 1"

**Version**
- In which version/build of the game did this happen?
LATEST VERSION 13-11

**To Reproduce**
1. Win a round
2. See Error

**Expected behavior**
I just want it to say PLAYER 1 WINS THE ROUND with no script name after it

**Desktop System (please complete the following information):**
- OS: Windows 10

**Comment by DanielPaulSwan** [comment]
Fixed while fixing Player Manager (All the bugs and issues with the Player Manager  have now been resolved)
