### ISSUE TITLE
Player Identifier

### ISSUE THREAD

**Issue by adamjamez** [DanielPaulSwan/TestEmperorPenguin#12]
**Describe the bug**
Currently it is difficult to identify which player is which as the Penguins look so similar.

**Version**
13 - 11

**To Reproduce**

**Expected behavior**
UI to allow for player identification.

**Screenshots**

**Desktop System (please complete the following information):**
- OS: [e.g. Windows10, Windows8.1, MacOSX]

**Additional context**
Will create UI coloured ring to be parented to each player at ground level to allow for identifier. Colours will match the player energy bar UI.

**Comment by DanielPaulSwan** [comment]
Light circles, colours and trails have been added to the penguins
