### ISSUE TITLE
Players Moving Before Round Starts

### ISSUE THREAD

**Issue by vittz** [DanielPaulSwan/TestEmperorPenguin#16]
**Describe the bug**

Players can move their characters around the iceberg before the countdown reaches 0. Need to disable their movement until the round officially starts.

**Version**
- In which version/build of the game did this happen?
latest version 13-11

**To Reproduce**
1. start game
2. move around
3. See error

**Expected behavior**
Players should be granted access to control their character once the round officially starts

**Desktop System (please complete the following information):**
- OS: Windows 10

**Comment by DanielPaulSwan** [comment]
Fixed When fixing another bug
