### ISSUE TITLE
Whale animation

### ISSUE THREAD

**Issue by adamjamez** [DanielPaulSwan/TestEmperorPenguin#17]
**Describe the bug**

The whale animation does not play when the scene is loaded.

**Version**
14 - 11

**To Reproduce**

**Expected behavior**
whale to animate when scene loads

**Screenshots**

**Desktop System (please complete the following information):**
- OS: [e.g. Windows10, Windows8.1, MacOSX]

**Additional context**

**Comment by DanielPaulSwan** [comment]
Was fixed  at some point. Not sure who did.
