### ISSUE TITLE
Crown Spawning from Round Manager not Working

### ISSUE THREAD

**Issue by DanielPaulSwan** [DanielPaulSwan/TestEmperorPenguin#2]
The crown can not be accessed by the RoundManager script causing some issues with the way it is spawned. Instantiating the object with a script is an issue since the spawn crown script is on the object spawned.

 Suggested that we instead enable / disable the crown rather than instantiating and destroying. Or we could instantiate as a child of an element holding the script. Either of these should solve the issue.

**Comment by DanielPaulSwan** [comment]
Although the crown now spawns from the manager, it spawns at odd times. Ie) If people die but the crown holder does not the crown is still respawned.

**Comment by vittz** [comment]
i believe i have fixed these issues :)
